all:

install:
	install -D net.gitit.App.desktop /app/share/applications/net.gitit.App.desktop
	install -D net.gitit.App.appdata.xml /app/share/appdata/net.gitit.App.appdata.xml
	install -D net.gitit.App.png /app/share/icons/hicolor/128x128/apps/net.gitit.App.png

.PHONY: all install
