#!/usr/bin/bash

set -e

prefix=$(cat prefix)
supdir="${prefix}/Gitit"
mkdir -p "${supdir}"
cp -a core "${supdir}"
find "${supdir}" -type d -a -name '.git' -print0 | xargs -0 rm -rf

bindir="${prefix}/bin"
mkdir -p "${bindir}"
escapedsupdir=$(echo "${supdir}" | sed -e 's/[\/&]/\\&/g')
sed -ie "s/@SUPDIR@/${escapedsupdir}/g" run-gitit
cp -a run-gitit "${bindir}"
